In [ ]:
import torch

## Basics of Tensor

In [ ]:
torch.empty(size=(2,3,4))

tensor([[[-1.5369e+29,  3.0882e-41,  7.0065e-44,  7.0065e-44],
         [ 6.3058e-44,  6.7262e-44,  6.8664e-44,  6.3058e-44],
         [ 6.8664e-44,  6.8664e-44,  1.1771e-43,  6.7262e-44]],

        [[ 7.8473e-44,  8.1275e-44,  7.1466e-44,  7.1466e-44],
         [ 8.1275e-44,  6.7262e-44,  7.4269e-44,  6.4460e-44],
         [ 7.0065e-44,  7.9874e-44,  7.5670e-44,  7.0065e-44]]])

In [ ]:
torch.ones(size=(3,4))*2

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [ ]:
t=torch.arange(6)
t.dtype

torch.int64

In [ ]:
t.double().dtype

torch.float64

In [ ]:
torch.linspace(start = 1 , end=20, steps=30).shape

torch.Size([30])

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
t=torch.tensor(arr)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
t=torch.from_numpy(arr)

In [ ]:
t.numpy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.tensor([1,2,3,4],dtype=torch.float32,device=device,requires_grad=True)

tensor([1., 2., 3., 4.], device='cuda:0', requires_grad=True)

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.diag(torch.tensor([1,2,3,5]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 5]])

In [ ]:
t= torch.rand(size=(4,4))
t

tensor([[0.9226, 0.8020, 0.0982, 0.4110],
        [0.3395, 0.5142, 0.0340, 0.7705],
        [0.9272, 0.9321, 0.5185, 0.3325],
        [0.1675, 0.0060, 0.5868, 0.8137]])

In [ ]:
torch.diag(t)

tensor([0.9226, 0.5142, 0.5185, 0.8137])

### Tensor Operation

In [ ]:
x = torch.ones(size=(3,4))
y = torch.ones(size=(3,4))*4

In [ ]:
print(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [ ]:
z=torch.empty(size=(3,4))

In [ ]:
torch.add(x,y,out=z)
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
z=torch.add(x,y)
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
z=x+y

In [ ]:
#x+=y
x.add_(y)
x

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
torch.arange(4)*3 <5


tensor([ True,  True, False, False])

In [ ]:
x.pow(2)

tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]])

In [ ]:
x = torch.ones(size=(3,4))
y = torch.ones(size=(4,5))*3

In [ ]:
torch.matmul(x,y)

tensor([[12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.]])

In [ ]:
batch=32
m=3
n=4
p=5

In [ ]:
x = torch.ones(size=(batch,m,n))
y = torch.ones(size=(batch,n,p))
torch.bmm(x,y).shape

torch.Size([32, 3, 5])

### Reshaping a tensor

In [ ]:
t=torch.tensor([1,2,3,4,5,6])
t.shape

torch.Size([6])

In [ ]:
t.unsqueeze(axis=1).squeeze()


tensor([1, 2, 3, 4, 5, 6])

In [ ]:
t=torch.arange(15)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
t.view(1,3,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
tensor=torch.linspace(0,10,24).reshape(2,3,4)


In [ ]:
tensor

tensor([[[ 0.0000,  0.4348,  0.8696,  1.3043],
         [ 1.7391,  2.1739,  2.6087,  3.0435],
         [ 3.4783,  3.9130,  4.3478,  4.7826]],

        [[ 5.2174,  5.6522,  6.0870,  6.5217],
         [ 6.9565,  7.3913,  7.8261,  8.2609],
         [ 8.6957,  9.1304,  9.5652, 10.0000]]])

In [ ]:
tensor[0][:,:2]

tensor([[0.0000, 0.4348],
        [1.7391, 2.1739],
        [3.4783, 3.9130]])

In [ ]:
tensor.shape

torch.Size([2, 3, 4])

In [ ]:
tensor.sum(axis=2)

tensor([[ 2.6087,  9.5652, 16.5217],
        [23.4783, 30.4348, 37.3913]])